### ISSUE TITLE
Merge the syntax for :memoize and :memoize_for_arguments

### ISSUE THREAD

**Issue by adlugopolski** [kjleitz/adornable#1]
Is there a technical reason to separate syntax to memoize methods with or without arguments? If method accepts any arguments it doesn't make much sense to memoize the same result for different arguments. I used to use the Memoist gem. The syntax there is the same regardless if the method accepts arguments. Arguments passed to the methods are always used as a part of the cache key.  

I am not sure if this qualifies as the issue per se. I guess this is a suggestion to just use one syntax for both variants. :-)

**Comment by kjleitz** [comment]
The only technical issue is that there's (currently) no way to pass arguments to the decorator! If you _could,_ then you could specify different functionality but use the same decorator method name. That would be a good addition, I think. It also gets it closer to replicating a "curried" function, which is generally how I think decorators should operate (but which is tough to do in a non-verbose way in Ruby).

How about this syntax?

```rb
class FooDecorators
  def self.punctuate(method_receiver, method_name, method_args, options)
    punctuation = options[:character] || "."
    "#{yield}#{punctuation}"
  end
end

class Foo
  add_decorators_from FooDecorators

  decorate :punctuate, options: { character: "!" }
  def cool
    "Cool"
  end

  decorate :punctuate, options: { character: "?" }
  def huh
    "Huh"
  end

  decorate :punctuate
  def whatever
    "Whatever"
  end

  decorate :memoize
  def foo
    # ...
  end

  decorate :memoize, options: { with_arguments: true }
  def bar
    # ...
  end
end

foo = Foo.new

foo.cool
#=> "Cool."

foo.huh
#=> "Huh?"

foo.whatever
#=> "Whatever."
```

Or maybe the decorator could take arbitrary keyword arguments after the required ones?

```rb
class FooDecorators
  def self.punctuate(method_receiver, method_name, method_args, character: ".")
    "#{yield}#{character}"
  end
end

class Foo
  # ...

  decorate :punctuate, character: "?"
  def huh
    "Huh"
  end

  decorate :memoize, with_arguments: true
  def bar
    # ...
  end
end
```

**Related:** I've been thinking it might end up being better to make _all_ the arguments to the decorator function keyword arguments, because then you'd only have to specify what you _need_ to receive, and you don't have to worry about parameter order:

```rb
class FooDecorators
  def self.decorator1(method_receiver:, method_name:, method_args:)
    ...
  end

  def self.decorator2(method_name:)
    # maybe you don't care about anything but the name
  end

  def self.decorator3(method_name:, method_receiver:)
    # don't need to worry about ordering
  end

  def self.decorator4
    # maybe you don't need to use any
  end
end
```

...or maybe they just receive one `options` parameter (a `Hash`) containing all the information about the decorated method, and any additional arguments passed to the decorator itself (which would be a good deal simpler, but not as explicit).

Have any opinions on this, @adlugopolski?

**Comment by adlugopolski** [comment]
@kjleitz Thank you for a very thorough answer. The ideas for decorator arguments are very interesting, but I was thinking about pointing a different issue here. I wanted to focus solely on memoization. I think that you should not distinguish between those two memoization cases. I think you should just use `decorator :memoize` for all cases. If the method actually accepts arguments you should always use their values as your "cache keys" for the result. 

I can't really imagine a case, when you would want to memoize result from a method regardless of the passed arguments. I can image many cases, when someone mixes up decorators. Another common pitfall  is when one changes the argument-less method to accept arguments and forgets to update the decorator. This seems like an easy pathway to undesired result.

I guess my suggestion is that you should remove `:memoize_for_arguments` variant entirely.

Currently the logic works like this in the example below. 

```ruby
class Person
  extend Adornable

  decorate :memoize
  def greet(name)
    "Hello #{name}"
  end
end

person = Person.new

person.hello("John")
# => "Hello John"

person.hello("Ava")
# => "Hello John"
```

Looking at the specs it seems that this behavior is desired and expected.

**Comment by kjleitz** [comment]
Great point @adlugopolski—I'll follow your suggestion. The behavior (by default) will be that arguments are **included** as part of the cache key. I'll keep argument exclusion as a keyword option, though, just in case. If anything, it'll be helpful as an example of passing parameters to a decorator.

**Comment by kjleitz** [comment]
@adlugopolski The `:memoize` decorator now uses the argument values by default in the latest release:

```rb
class Foo
  extend Adornable

  decorate :memoize
  def some_method(req_arg, opt_arg = 123, req_kwarg:, opt_kwarg: 123)
    rand
  end
end

foo = Foo.new

foo.some_method(123, req_kwarg: 123)
#=> 0.6964898722418218
foo.some_method(123, req_kwarg: 123)
#=> 0.6964898722418218
foo.some_method(456, req_kwarg: 123)
#=> 0.16820845794949157
foo.some_method(456, true, req_kwarg: 123, opt_kwarg: true)
#=> 0.16820845794949157
foo.some_method(456, true, req_kwarg: 123, opt_kwarg: false)
#=> 0.32855856114741455

# ...etc.; caches based on argument values
```

I left in an option to ignore the argument values as they relate to caching and simply memoize the result entirely:

```rb
class Foo
  extend Adornable

  decorate :memoize, for_any_arguments: true
  def some_method(req_arg, opt_arg = 123, req_kwarg:, opt_kwarg: 123)
    rand
  end
end

foo = Foo.new

foo.some_method(123, req_kwarg: 123)
#=> 0.25725452949328553
foo.some_method(123, req_kwarg: 123)
#=> 0.25725452949328553
foo.some_method(456, req_kwarg: 123)
#=> 0.25725452949328553
foo.some_method(456, true, req_kwarg: 123, opt_kwarg: true)
#=> 0.25725452949328553
foo.some_method(456, true, req_kwarg: 123, opt_kwarg: false)
#=> 0.25725452949328553

# ...etc.; caches based on argument values
```

Which, I imagine, _could be_ a legitimate use case (if a bit uncommon/unusual):

```rb
class Foo
  extend Adornable

  decorate :memoize, for_any_arguments: true
  def created_at=(datetime)
    @created_at = datetime
  end
end

foo = Foo.new

foo.created_at = Time.now
#=> 2021-02-17 10:48:07.457741913 -0500

# A few seconds later...
sleep 10

foo.created_at = Time.now
#=> 2021-02-17 10:48:07.457741913 -0500
```

**Comment by adlugopolski** [comment]
Wow, this was really fast and slick, thanks! 👍 😄
